### ISSUE TITLE
[query] single-cell roadmap

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13559]
### What happened?

Short term:

- [ ] block-partitioning of a matrix table
- [ ] transposition of a matrix table

Long term (5 year horizon):

- [ ] PCA on a matrix where both axes are 2M or longer (e.g. we have 1M people each with 1M cells and we want PCA of that matrix).

### Version

0.2.120

**Comment by danking** [comment]
Replacing with concrete issues:

1. https://github.com/hail-is/hail/issues/13800
2. https://github.com/hail-is/hail/issues/13801

I'm dropping transposition for now but it's a natural operation to add after #13800
