### ISSUE TITLE
[pipeline] To-Do Items

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#5380]
- [ ] Enable pipelines to be able to run in the background for both Local and Batch modes
- [ ] Add dry-run support to BatchBackend
- [ ] Don't serially copy files in BatchBackend
- [ ] Docker within docker needs to work to test the LocalBackend docker mode
