### ISSUE TITLE
[batch] meta-issue 30k pod scale tests

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6547]
This test:

```python3
p = Pipeline(backend=BatchBackend('https://batch.hail.is'))
for _ in range(30000):
    p.new_task().command('/bin/true')
p.run()
```

Revealed a number of issues:
daniel king: Problems Found:
- [x] https://github.com/hail-is/hail/issues/6543 mysql can deadlock itself, requiring you to reissue the db request
- [x] https://github.com/hail-is/hail/issues/6545 of the 20760 pods that were successfully created before #6543 happened, about 800 could not get their logs due to not existing. That's a failure rate of ~4%. The number of failures continues to grow as I type this message (now up to 1280). I'm counting failures this way:
```
k logs -l app=batch --tail=999999 | grep 'no logs for ' | sed -E 's/^.*no logs for ([^ ]+).*$/\1/' | sort -u | wc -l
```
- the k8s request latency spiked to 3.47s max 0.6 s mean during this test and stayed elevated for 10 minutes.
- [ ] https://github.com/hail-is/hail/issues/6546 there was a lot of volume mount failures due to, apparently, the secrets, e.g.:
```
9m13s       Warning   FailedMount              Pod                     Unable to mount volumes for pod "batch-278-job-10258-a49a81_batch-pods(82ea5910-9ccb-11e9-ad88-42010a800049)": timeout expired waiting for volumes to attach or mount for pod "batch-pods"/"batch-278-job-10258-a49a81". list of unmounted volumes=[gsa-key default-token-8h99c]. list of unattached volumes=[gsa-key default-token-8h99c]
```
- [ ] https://github.com/hail-is/hail/issues/6548 batch takes 4 seconds to render the batch page with 20k jobs (the web browser displays it fine though), e.g. https://batch.hail.is/batches/278
- [ ] https://github.com/hail-is/hail/issues/6548 batch UI search is DOA with 20k jobs
- [ ] https://github.com/hail-is/hail/issues/6556 delete (and likely cancel) will timeout on large batches
