### ISSUE TITLE
[datasets] Hail Datasets Todo

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6715]
- [x] DANN, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4341060/
- [x] CADD, http://europepmc.org/abstract/med/11384848
- [x] reference genomes 95, GRCh37 & 38., https://useast.ensembl.org/index.html
- [x] low complexity regions 95, GRCh37 & 38, https://useast.ensembl.org/index.html
- [x] Gencode (names and gene metadata) v19 GRCh37, v38 GRCh38, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3431492/, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3431492/
- [x] gnomAD LOF by gene, https://gnomad.broadinstitute.org/
- [x] gnomAD sites exomes & genomes (includes VEP, AF, etc.), https://gnomad.broadinstitute.org/
- [ ] MAF for 1KG, should be in the VCFs which are available via FTP here: http://www.internationalgenome.org/data
- [ ] VEP (?? need more information about what is requested)
- [ ] which allele is ancestral (?? Elizabeth has more info?)
- [X] clinvar for GRCh37 & 38
- [ ] LCR (?? is gnomAD sufficient?)
- [ ] GERP or other sequence conservation score
- [ ] major exome platform capture areas (?? need more information)
- [ ] All the missense annotation scores (from dbNSFP, ftp://dbnsfp.softgenetics.com/dbNSFP4.0a.zip)

**Comment by danking** [comment]
We should probably talk to the SEQR team as well: https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py
