### ISSUE TITLE
FAQ To-Do Items

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#812]
See the FAQ Style Guide.

**Annotations**
- [ ] Do I need to define the types when using `annotatesamples table`?
- [ ] How does Hail annotate variants overlapping different intervals in an interval list?
- [ ] How do I input phenotype information into Hail?
- [ ] Is there a way to see all annotations present in the dataset?

**Expression Language**
- [ ] Can I use regular expressions in the Hail expression language?
- [ ] how can i filter samples based on whether or not they have a particular variant?

**Data Representation**
- [ ] How are insertion and deletion variants coded in the VDS?
- [ ] How are the boundaries for Pseudo-autosomal variants determined?

**Exporting Data**
- [ ] How can I export all global annotations to a file?
- [ ] How do I export my data so there are separate VCFs per chromosome?
- [ ] How do I export my annotations as a JSON file?
- [ ] How do I export updated call statistics (AC, AF) to the info field of the VCF?

**Developer Tools**
- [ ] Is there a style guide I should use for IntelliJ?

**Importing Data**
- [ ] How do I import data from a VCF file?
- [ ] How do I import annotations in JSON format?
- [ ] Is the UCSC file 0 or 1 based?

**Methods**
- [ ] Does Hail handle sex chromosomes differently in variantqc and sampleqc?
- [ ] How do I parse the variant annotations from VEP to find the worst functional consequence?
- [ ] How do I find all variants where the functional change on the canonical transcript results in a missense mutation?
- [ ] Is rHetHom calculated over indels+SNPs or just SNPs?
- [ ] Are sampleqc and variantqc calculated only on PASS variants?

**Optimize Pipeline**
- [ ] When should I write my data to a VDS file?

**Comment by cseed** [comment]
- [ ] https://github.com/hail-is/hail/issues/803

**Comment by jigold** [comment]
- [ ] Document temp directory differences, see: #902

**Comment by jbloom22** [comment]
The FAQ is gone.  These should go in documentation of commands, or more likely as discussion forum questions and answers.

**Comment by cseed** [comment]
FAQ gone, marking this moved and closed.
